Repository dedis/cothority, pull requests merged in 2019-10, with the labels that each got.

#2077 Proposal for error-handling
  .github/PULL_REQUEST_TEMPLATE.md
Labels: question

#2082 Fixes personhood contracts
  external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java
  external/js/cothority/src/byzcoin/byzcoin-rpc.ts
  go.mod
  personhood/contract_ropasci.go
  personhood/contract_ropasci_test.go
  personhood/contract_spawner.go
  personhood/contract_test.go
  personhood/proto.go
Labels: fix

#2086 Fixes some race conditions
  byzcoin/api.go
  byzcoin/bcadmin/clicontracts/deferred.go
  byzcoin/bcadmin/commands.go
  byzcoin/bcadmin/lib/utils.go
  byzcoin/bcadmin/main.go
  byzcoin/bcadmin/test.sh
  byzcoin/proof.go
Labels: fix

#2093 add calypso ropascis to personhood
  external/js/cothority/src/personhood/credentials-instance.ts
  external/js/cothority/src/personhood/pop-party-instance.ts
  external/js/cothority/src/personhood/ro-pa-sci-instance.ts
  external/js/cothority/src/personhood/spawner-instance.ts
  personhood/contract_popparty.go
Labels: enhancement

#2097 Updates the doctoc.sh and the conode/ doc
  conode/README.md
  doctoc.sh
Labels: enhancement, fix

#2096 Adds some instructions on how to build `external/`
  external/Makefile
  external/README.md
Labels: enhancement

#2090 more advanced connection handling
  external/js/cothority/spec/byzcoin/coin-instance.spec.ts
  external/js/cothority/spec/network/connection.spec.ts
  external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts
  external/js/cothority/spec/support/conondes.ts
  external/js/cothority/src/byzcoin/byzcoin-rpc.ts
  external/js/cothority/src/calypso/calypso-rpc.ts
  external/js/cothority/src/log.ts
  external/js/cothority/src/network/connection.ts
  external/js/cothority/src/network/nodes.ts
  external/js/cothority/src/skipchain/skipchain-rpc.ts
  external/js/cothority/src/status/status-rpc.ts
  external/js/cothority/tslint.json
  go.sum
  skipchain/skipchain.go
Labels: enhancement

#2102 Errors handling byzcoin
  byzcoin/api.go
  byzcoin/api_test.go
  byzcoin/bcadmin/clicontracts/config.go
  byzcoin/bcadmin/clicontracts/deferred.go
  byzcoin/bcadmin/clicontracts/name.go
  byzcoin/bcadmin/clicontracts/value.go
  byzcoin/bcadmin/cmd_db.go
  byzcoin/bcadmin/lib/config.go
  byzcoin/bcadmin/lib/utils.go
  byzcoin/bcadmin/main.go
  byzcoin/collect_tx.go
  byzcoin/contract_darc.go
  byzcoin/contract_deferred.go
  byzcoin/contract_name.go
  byzcoin/contracts.go
  byzcoin/contracts/attr_test.go
  byzcoin/contracts/coins.go
  byzcoin/contracts/coins_test.go
  byzcoin/contracts/insecure_darc.go
  byzcoin/contracts/value.go
  byzcoin/heartbeat.go
  byzcoin/proof.go
  byzcoin/proof_test.go
  byzcoin/replayguard.go
  byzcoin/service.go
  byzcoin/service_test.go
  byzcoin/simulation/coins.go
  byzcoin/statechange_cache.go
  byzcoin/statereplay.go
  byzcoin/statereplay_test.go
  byzcoin/statetrie.go
  byzcoin/statetrie_test.go
  byzcoin/struct.go
  byzcoin/transaction.go
  byzcoin/trie/db_test.go
  byzcoin/trie/dfs.go
  byzcoin/trie/diskdb.go
  byzcoin/trie/memdb.go
  byzcoin/trie/metadata.go
  byzcoin/trie/node.go
  byzcoin/trie/proof.go
  byzcoin/trie/staging.go
  byzcoin/trie/staging_test.go
  byzcoin/trie/trie.go
  byzcoin/trie/trie_test.go
  byzcoin/tx_pipeline.go
  byzcoin/tx_pipeline_test.go
  byzcoin/viewchange.go
  byzcoin/wallet/main.go
  error.go
  error_test.go
  go.mod
  go.sum
Labels: take-for-v3

#2106 Fix issue with isSecureContext with local content
  external/js/cothority/package-lock.json
  external/js/cothority/package.json
  external/js/cothority/spec/helpers/global-this.ts
  external/js/cothority/spec/network/connection.spec.ts
  external/js/cothority/src/network/connection.ts
Labels: take-for-v3

#2110 Minor improvement on the cothority/index.html
  external/js/cothority/index.html
Labels: enhancement, external / js

#2115 Fixes a csadmin test
  calypso/csadmin/clicontracts/write.go
  calypso/csadmin/commands.go
Labels: Calypso, easy review, fix, take-for-v3

#2101 Bcadmin usability
  .gitignore
  byzcoin/bcadmin/commands.go
  byzcoin/bcadmin/lib/config.go
  byzcoin/bcadmin/main.go
  byzcoin/bcadmin/test.sh
Labels: ByzCoin, enhancement, feature, fix, take-for-v3

#2126 correctly print message
  byzcoin/viewchange.go
Labels: take-for-v3

#2122 Atomically commit forward-link and new block
  byzcoin/api.go
  byzcoin/bcadmin/lib/utils.go
  byzcoin/service.go
  byzcoin/service_test.go
  byzcoin/viewchange_test.go
  calypso/service_test.go
  dkg/pedersen/dkg.go
  skipchain/skipchain.go
  skipchain/struct.go
Labels: take-for-v3

#2117 Add LTS info
  calypso/csadmin/README.md
  calypso/csadmin/commands.go
  calypso/csadmin/main.go
  calypso/csadmin/test.sh
  conode/run_nodes.sh
Labels: take-for-v3

#2128 Clean the block-cache correctly
  byzcoin/viewchange.go
  skipchain/skipchain.go
Labels: take-for-v3
