Repository dedis/cothority, pull requests merged in 2020-06, with the labels that each got.

#2306 test{F,}Grep(): display output when failing
  libtest.sh
Labels: easy review, enhancement, testing

#2313 travis: go mod tidy done by Coding
  .travis.yml
Labels: easy review

#2285 Use dedis/onet#640 to filter ByzCoin connections
  byzcoin/service.go
  byzcoin/service_test.go
  calypso/proto.go
  calypso/service.go
  external/java/src/main/java/ch/epfl/dedis/lib/proto/Calypso.java
  external/js/cothority/src/protobuf/models.json
  external/proto/calypso.proto
  go.mod
  go.sum
Labels: ByzCoin, feature
