Repository dedis/cothority, pull requests merged in 2020-03, with the labels that each got.

#2220 Bevm calls byzcoin
  bevm/bevm_attr_test.go
  bevm/bevm_call_byzcoin.go
  bevm/bevm_call_byzcoin_test.go
  bevm/bevm_client.go
  bevm/bevm_contract.go
  bevm/bevm_contract_test.go
  bevm/bevmclient/cmd_imp.go
  bevm/database_byz.go
  bevm/testdata/CallByzcoin/CallByzcoin.sol
  bevm/testdata/CallByzcoin/CallByzcoin_sol_CallByzcoin.abi
  bevm/testdata/CallByzcoin/CallByzcoin_sol_CallByzcoin.bin
  byzcoin/contracts.go
  byzcoin/contracts/coins_test.go
  byzcoin/proto.go
  byzcoin/service.go
  byzcoin/statetrie.go
  byzcoin/transaction.go
  byzcoin/trie/staging.go
  byzcoin/trie/trie.go
  darc/darc.go
  darc/darc_test.go
  darc/expression/expression.go
  darc/proto.go
  external/js/cothority/src/protobuf/models.json
  external/proto/byzcoin.proto
  external/proto/darc.proto
  personhood/contracts/contract_test.go
Labels: feature

#2212 gofmt -simplify
  byzcoin/api_test.go
  byzcoin/collect_tx_test.go
  byzcoin/service_test.go
  byzcoin/statereplay_test.go
  byzcoin/viewchange.go
  darc/darc_test.go
  skipchain/skipchain_test.go
  skipchain/struct_test.go
Labels: easy review, enhancement

#2226 external/cothority: run tests before publish
  .travis.yml
  external/js/cothority/package.json
  external/js/kyber/package.json
Labels: easy review, external / js, integration, release engineering

#2231 `go mod tidy` travis pass
  .travis.yml
  go.sum
Labels: easy review, integration

#2235 travis: revert to old npm publish
  .travis.yml
Labels: easy review, fix, high priority, integration

#2238 travis: publish -> publish.sh
  .travis.yml
Labels: fix, high priority, integration
